/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package header;
import admin.loginadmin;
import user.LogIn;

/**
 *
 * @author Yoga Asta
 */
public class Headerframe extends javax.swing.JFrame {

    /**
     * Creates new form FrameAdmin
     */
    public Headerframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keluar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel2 = new javax.swing.JPanel();
        adminbtn = new javax.swing.JButton();
        memberbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1101, 633));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1101, 633));
        getContentPane().setLayout(null);

        keluar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        keluar.setText("X");
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(1070, 0, 20, 30);

        jPanel3.setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 51, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 0));
        kGradientPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jPanel2.setLayout(null);

        adminbtn.setBackground(new java.awt.Color(255, 255, 255));
        adminbtn.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        adminbtn.setText("ADMIN");
        adminbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        adminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtnActionPerformed(evt);
            }
        });
        jPanel2.add(adminbtn);
        adminbtn.setBounds(110, 90, 244, 242);

        memberbtn.setBackground(new java.awt.Color(255, 255, 255));
        memberbtn.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        memberbtn.setText("SISWA");
        memberbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        memberbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberbtnActionPerformed(evt);
            }
        });
        jPanel2.add(memberbtn);
        memberbtn.setBounds(480, 90, 244, 242);

        kGradientPanel1.add(jPanel2);
        jPanel2.setBounds(170, 200, 800, 390);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("PILIH STATUS ANDA");
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(470, 160, 250, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/user.png"))); // NOI18N
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(510, 70, 90, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/user.png"))); // NOI18N
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(470, 90, 80, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/user.png"))); // NOI18N
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(590, 70, 90, 90);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/user.png"))); // NOI18N
        kGradientPanel1.add(jLabel5);
        jLabel5.setBounds(550, 60, 90, 90);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/user.png"))); // NOI18N
        kGradientPanel1.add(jLabel6);
        jLabel6.setBounds(630, 90, 80, 80);

        jPanel3.add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 1100, 640);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1100, 630);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtnActionPerformed
        // TODO add your handling code here:
        loginadmin newadmin = new loginadmin();
        newadmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminbtnActionPerformed

    private void memberbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberbtnActionPerformed
        // TODO add your handling code here:
        LogIn regismember = new LogIn();
        regismember.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_memberbtnActionPerformed

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Headerframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Headerframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Headerframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Headerframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Headerframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel keluar;
    private javax.swing.JButton memberbtn;
    // End of variables declaration//GEN-END:variables
}
