/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;
/**
 *
 * @author Yoga Asta
 */
import database.koneksi;
import tampilan.dashboardframe;
import header.Headerframe;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Object set;
    
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel2 = new javax.swing.JPanel();
        judul_menu_login = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        lupa_pass = new javax.swing.JLabel();
        isi_email = new javax.swing.JTextField();
        isi_username = new javax.swing.JTextField();
        isi_pass = new javax.swing.JPasswordField();
        tbl_reg = new javax.swing.JButton();
        tbl_login = new javax.swing.JButton();
        USERNAMELBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbl_mimizenexit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1106, 530));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1106, 530));
        getContentPane().setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 51));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 255, 204));
        kGradientPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        judul_menu_login.setFont(new java.awt.Font("News701 BT", 1, 24)); // NOI18N
        judul_menu_login.setForeground(new java.awt.Color(204, 204, 204));
        judul_menu_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/login.png"))); // NOI18N
        jPanel2.add(judul_menu_login);
        judul_menu_login.setBounds(340, -10, 120, 130);

        email.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/mail.png"))); // NOI18N
        jPanel2.add(email);
        email.setBounds(210, 220, 50, 30);

        pass.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/padlock.png"))); // NOI18N
        jPanel2.add(pass);
        pass.setBounds(210, 300, 80, 40);

        lupa_pass.setForeground(new java.awt.Color(255, 0, 0));
        lupa_pass.setText("FORGOT PASSWORD?");
        lupa_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupa_passMouseClicked(evt);
            }
        });
        jPanel2.add(lupa_pass);
        lupa_pass.setBounds(330, 450, 150, 16);

        isi_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        isi_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isi_emailActionPerformed(evt);
            }
        });
        jPanel2.add(isi_email);
        isi_email.setBounds(240, 250, 300, 30);

        isi_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        isi_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isi_usernameActionPerformed(evt);
            }
        });
        jPanel2.add(isi_username);
        isi_username.setBounds(240, 170, 300, 30);

        isi_pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(isi_pass);
        isi_pass.setBounds(240, 340, 300, 30);

        tbl_reg.setBackground(new java.awt.Color(255, 255, 255));
        tbl_reg.setText("SIGN UP");
        tbl_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl_regActionPerformed(evt);
            }
        });
        jPanel2.add(tbl_reg);
        tbl_reg.setBounds(340, 420, 90, 25);

        tbl_login.setBackground(new java.awt.Color(255, 255, 255));
        tbl_login.setText("SIGN IN");
        tbl_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl_loginActionPerformed(evt);
            }
        });
        jPanel2.add(tbl_login);
        tbl_login.setBounds(340, 380, 90, 25);

        USERNAMELBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/user.png"))); // NOI18N
        USERNAMELBL.setText("USERNAME");
        jPanel2.add(USERNAMELBL);
        USERNAMELBL.setBounds(210, 120, 70, 50);

        jLabel1.setText("USERNAME");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(280, 140, 100, 30);

        jLabel2.setText("EMAIL");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(280, 220, 50, 30);

        jLabel3.setText("PASSWORD");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(270, 310, 70, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("LOGIN");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(370, 100, 70, 22);

        kGradientPanel1.add(jPanel2);
        jPanel2.setBounds(189, 23, 781, 494);

        tbl_mimizenexit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbl_mimizenexit.setText("   X");
        tbl_mimizenexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mimizenexitMouseClicked(evt);
            }
        });
        kGradientPanel1.add(tbl_mimizenexit);
        tbl_mimizenexit.setBounds(1063, 0, 40, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/previous (1).png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel5);
        jLabel5.setBounds(10, 0, 50, 40);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 1110, 530);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl_loginActionPerformed
        // TODO add your handling code here:
        conn = koneksi.getkoneksi();
        String sql = "SELECT * FROM tb_user WHERE nama=? and email=? and pass=?";
        try{
            pst = (PreparedStatement)conn.prepareStatement(sql);
            pst.setString(1, isi_username.getText());
            pst.setString(2, isi_email.getText());
            pst.setString(3, isi_pass.getText());
            rs = pst.executeQuery();
            System.out.println(rs);
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Aktivitas Login Anda Sukses!!");
                dashboardframe framedashboard = new dashboardframe();
                framedashboard.setVisible(true);
                this.dispose();
               
                 System.out.println(rs);
            }else{
                JOptionPane.showMessageDialog(null, "Data Yang Anda Masukan Salah!!!", "Pesan", JOptionPane.ERROR_MESSAGE);
               
                isi_username.setText("");
                isi_email.setText("");
                isi_pass.setText("");
            }
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
     
    }//GEN-LAST:event_tbl_loginActionPerformed

    private void isi_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isi_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isi_usernameActionPerformed

    private void isi_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isi_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isi_emailActionPerformed

    private void tbl_mimizenexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mimizenexitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tbl_mimizenexitMouseClicked

    private void tbl_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl_regActionPerformed
        // TODO add your handling code here:
        regis frameregis = new regis();
        frameregis.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_tbl_regActionPerformed

    private void lupa_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupa_passMouseClicked
        // TODO add your handling code here:
        forgot_pass lupa_pass = new forgot_pass();
        lupa_pass.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lupa_passMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Headerframe header = new Headerframe();
        header.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel USERNAMELBL;
    private javax.swing.JLabel email;
    private javax.swing.JTextField isi_email;
    private javax.swing.JPasswordField isi_pass;
    private javax.swing.JTextField isi_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel judul_menu_login;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lupa_pass;
    private javax.swing.JLabel pass;
    private javax.swing.JButton tbl_login;
    private javax.swing.JLabel tbl_mimizenexit;
    private javax.swing.JButton tbl_reg;
    // End of variables declaration//GEN-END:variables
}
