/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;
 import database.koneksi;
    import java.sql.Connection;
    import java.sql.PreparedStatement;
    import java.sql.SQLException;
    import java.text.SimpleDateFormat;
    import javax.swing.JOptionPane;
    import java.sql.DriverManager;

/**
 *
 * @author Yoga Asta
 */
public class regis extends javax.swing.JFrame {
    private Connection conn = new koneksi().getkoneksi();

protected void aktif(){
    input_nama.setEnabled(true);
    input_alamat.setEnabled(true);
    input_EMAIL.setEnabled(true);
    isi_password.setEnabled(true);
    input_nama.requestFocus();
}
protected void kosong(){
    input_nama.setText("");
    input_alamat.setText("");
    input_EMAIL.setText("");
    isi_password.setText("");
}

    /**
     * Creates new form regis
     */
    public regis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        input_alamat = new javax.swing.JTextField();
        input_nama = new javax.swing.JTextField();
        input_EMAIL = new javax.swing.JTextField();
        isi_password = new javax.swing.JPasswordField();
        input_ulang_pass = new javax.swing.JPasswordField();
        tbl_registrasi = new javax.swing.JButton();
        opsi_login = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1220, 549));
        setUndecorated(true);
        getContentPane().setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 0));
        kGradientPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/registered.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(400, 0, 90, 110);

        jLabel2.setText("USERNAME");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(170, 160, 80, 16);

        jLabel3.setText("ALAMAT");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(170, 200, 48, 16);

        jLabel4.setText("EMAIL");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(170, 240, 35, 16);

        jLabel5.setText("PASSWORD");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(170, 280, 90, 16);

        jLabel6.setText("ULANG PASSWORD");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(170, 330, 130, 16);

        input_alamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(input_alamat);
        input_alamat.setBounds(300, 200, 349, 18);

        input_nama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        input_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_namaActionPerformed(evt);
            }
        });
        jPanel2.add(input_nama);
        input_nama.setBounds(300, 160, 349, 18);

        input_EMAIL.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(input_EMAIL);
        input_EMAIL.setBounds(300, 240, 349, 18);

        isi_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(isi_password);
        isi_password.setBounds(300, 280, 349, 18);

        input_ulang_pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(input_ulang_pass);
        input_ulang_pass.setBounds(300, 330, 349, 18);

        tbl_registrasi.setBackground(new java.awt.Color(255, 255, 255));
        tbl_registrasi.setText("REGISTRASI");
        tbl_registrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl_registrasiActionPerformed(evt);
            }
        });
        jPanel2.add(tbl_registrasi);
        tbl_registrasi.setBounds(410, 370, 130, 40);

        opsi_login.setBackground(new java.awt.Color(255, 51, 0));
        opsi_login.setForeground(new java.awt.Color(255, 51, 0));
        opsi_login.setText("SUDAH PUNYA AKUN ?");
        opsi_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opsi_loginMouseClicked(evt);
            }
        });
        jPanel2.add(opsi_login);
        opsi_login.setBounds(560, 380, 140, 16);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("---REGISTRASI---");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(370, 110, 160, 30);

        kGradientPanel1.add(jPanel2);
        jPanel2.setBounds(180, 50, 855, 447);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel8);
        jLabel8.setBounds(1190, 0, 20, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1220, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void input_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_namaActionPerformed

    private void tbl_registrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl_registrasiActionPerformed
        // TODO add your handling code here:
         String sql = "insert into tb_user values(?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, input_nama.getText());
            stat.setString(2, input_alamat.getText());
            stat.setString(3, input_EMAIL.getText());
            stat.setString(4, isi_password.getText());

            if (isi_password.getText().equals(input_ulang_pass.getText())){
                if(input_nama.getText().equals("") || input_nama.getText().equals("") || input_nama.getText().equals("")
                    || input_ulang_pass.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Tolong Masukan Data Anda");
                }else{
                    Connection konekDatabase = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/db_admsekolah", "root", "");

                    JOptionPane.showMessageDialog(this,"Register Berhasil","Notifikasi",JOptionPane.INFORMATION_MESSAGE);
                    stat.executeUpdate();
                    kosong();
                    jLabel1.setText("");

                    LogIn lg= new LogIn();
                    lg.setVisible(true);
                    lg.pack();
                    lg.setLocationRelativeTo(null);
                    lg.setDefaultCloseOperation(regis.EXIT_ON_CLOSE);
                    this.dispose();
                }
            }else{
                jLabel1.setText("Password yang anda masukkan salah !(red)" );
            }

            input_nama.requestFocus();

        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Registrasi Anda Gagal" );
        }

    }//GEN-LAST:event_tbl_registrasiActionPerformed

    private void opsi_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opsi_loginMouseClicked
        // TODO add your handling code here:
        LogIn framelogin = new LogIn();
        framelogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_opsi_loginMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField input_EMAIL;
    private javax.swing.JTextField input_alamat;
    private javax.swing.JTextField input_nama;
    private javax.swing.JPasswordField input_ulang_pass;
    private javax.swing.JPasswordField isi_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel opsi_login;
    private javax.swing.JButton tbl_registrasi;
    // End of variables declaration//GEN-END:variables
}
