/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
    import database.koneksi;
    import java.sql.Connection;
    import java.sql.PreparedStatement;
    import java.sql.SQLException;
    import java.text.SimpleDateFormat;
    import javax.swing.JOptionPane;
    import java.sql.DriverManager;

import javax.swing.JOptionPane;

/**
 *
 * @author Yoga Asta
 */
import user.LogIn;
public class dashboardframe extends javax.swing.JFrame {
    private Connection conn = new koneksi().getkoneksi();
   
    protected void aktif(){
    namafield.setEnabled(true);
    kelasfield.setEnabled(true);
    nisfield.setEnabled(true);
    rekfield.setEnabled(true);
    nominalfield.setEnabled(true);
    deskripsitxt.setEnabled(true);
    namafield.requestFocus();
}
protected void kosong(){
    namafield.setText("");
    kelasfield.setText("");
    nisfield.setText("");
    rekfield.setText("");
    nominalfield.setText("");
    deskripsitxt.setText("");
}

    /**
     * Creates new form dashboardframe
     */
    public dashboardframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        homepng = new javax.swing.JLabel();
        aboutpng = new javax.swing.JLabel();
        contactpng = new javax.swing.JLabel();
        logoutpng = new javax.swing.JLabel();
        homebtn = new javax.swing.JButton();
        aboutbtn = new javax.swing.JButton();
        contactbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        judulpng = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        abstractpanel = new javax.swing.JPanel();
        homepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        aboutpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        contactpanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pembayaran = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        namafield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kelasfield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nisfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rekfield = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nominalfield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deskripsitxt = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        lunas = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        exitbtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1102, 639));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1102, 639));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1064, 639));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, new java.awt.Color(0, 0, 0), java.awt.Color.black, java.awt.Color.black));
        jPanel2.setLayout(null);

        homepng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/home.png"))); // NOI18N
        jPanel2.add(homepng);
        homepng.setBounds(10, 270, 50, 40);

        aboutpng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/information-button.png"))); // NOI18N
        jPanel2.add(aboutpng);
        aboutpng.setBounds(10, 350, 50, 40);

        contactpng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/call.png"))); // NOI18N
        jPanel2.add(contactpng);
        contactpng.setBounds(10, 430, 60, 40);

        logoutpng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/logout.png"))); // NOI18N
        jPanel2.add(logoutpng);
        logoutpng.setBounds(10, 530, 50, 30);

        homebtn.setBackground(new java.awt.Color(255, 255, 255));
        homebtn.setText("         HOME");
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        jPanel2.add(homebtn);
        homebtn.setBounds(10, 260, 133, 66);

        aboutbtn.setBackground(new java.awt.Color(255, 255, 255));
        aboutbtn.setText("         ABOUT");
        aboutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutbtnActionPerformed(evt);
            }
        });
        jPanel2.add(aboutbtn);
        aboutbtn.setBounds(14, 342, 133, 67);

        contactbtn.setBackground(new java.awt.Color(255, 255, 255));
        contactbtn.setText("           CONTACT");
        contactbtn.setIconTextGap(10);
        contactbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactbtnActionPerformed(evt);
            }
        });
        jPanel2.add(contactbtn);
        contactbtn.setBounds(14, 422, 133, 68);

        logoutbtn.setBackground(new java.awt.Color(255, 255, 255));
        logoutbtn.setText("       LOGOUT");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        jPanel2.add(logoutbtn);
        logoutbtn.setBounds(14, 508, 133, 66);

        judulpng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/mortarboard.png"))); // NOI18N
        jPanel2.add(judulpng);
        judulpng.setBounds(30, 30, 90, 90);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("E - STUDENT");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 110, 90, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(12, 13, 160, 610);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jPanel3.setLayout(new java.awt.CardLayout());

        abstractpanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout abstractpanelLayout = new javax.swing.GroupLayout(abstractpanel);
        abstractpanel.setLayout(abstractpanelLayout);
        abstractpanelLayout.setHorizontalGroup(
            abstractpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
        );
        abstractpanelLayout.setVerticalGroup(
            abstractpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        jPanel3.add(abstractpanel, "card4");

        homepanel.setBackground(new java.awt.Color(255, 255, 255));
        homepanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("--HOME--");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/graduates (1).png"))); // NOI18N
        jButton1.setText("PROFILE");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/shopping-cart.png"))); // NOI18N
        jButton2.setText("PEMBAYARAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homepanelLayout = new javax.swing.GroupLayout(homepanel);
        homepanel.setLayout(homepanelLayout);
        homepanelLayout.setHorizontalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(404, 404, 404))
        );
        homepanelLayout.setVerticalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addContainerGap(379, Short.MAX_VALUE))
        );

        jPanel3.add(homepanel, "card2");

        aboutpanel.setBackground(new java.awt.Color(22, 160, 133));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("--ABOUT--");

        javax.swing.GroupLayout aboutpanelLayout = new javax.swing.GroupLayout(aboutpanel);
        aboutpanel.setLayout(aboutpanelLayout);
        aboutpanelLayout.setHorizontalGroup(
            aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutpanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addContainerGap(746, Short.MAX_VALUE))
        );
        aboutpanelLayout.setVerticalGroup(
            aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutpanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addContainerGap(550, Short.MAX_VALUE))
        );

        jPanel3.add(aboutpanel, "card3");

        contactpanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("--CONTACT-- ");

        javax.swing.GroupLayout contactpanelLayout = new javax.swing.GroupLayout(contactpanel);
        contactpanel.setLayout(contactpanelLayout);
        contactpanelLayout.setHorizontalGroup(
            contactpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactpanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(727, Short.MAX_VALUE))
        );
        contactpanelLayout.setVerticalGroup(
            contactpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactpanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(561, Short.MAX_VALUE))
        );

        jPanel3.add(contactpanel, "card5");

        pembayaran.setBackground(new java.awt.Color(255, 255, 255));
        pembayaran.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("PEMBAYARAN");
        pembayaran.add(jLabel5);
        jLabel5.setBounds(357, 67, 172, 28);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel4.setLayout(null);

        jLabel6.setText("NAMA");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(61, 42, 34, 16);
        jPanel4.add(namafield);
        namafield.setBounds(206, 39, 311, 22);

        jLabel7.setText("KELAS");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(61, 102, 36, 16);
        jPanel4.add(kelasfield);
        kelasfield.setBounds(206, 99, 311, 22);

        jLabel8.setText("NIS");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(61, 159, 20, 16);
        jPanel4.add(nisfield);
        nisfield.setBounds(206, 156, 311, 22);

        jLabel9.setText("NO REKENING");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(61, 215, 78, 16);
        jPanel4.add(rekfield);
        rekfield.setBounds(206, 212, 311, 22);

        jLabel10.setText("NOMINAL");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(61, 269, 53, 16);
        jPanel4.add(nominalfield);
        nominalfield.setBounds(206, 266, 311, 22);

        jLabel11.setText("DESKRIPSI");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(61, 321, 61, 16);

        deskripsitxt.setColumns(20);
        deskripsitxt.setRows(5);
        jScrollPane1.setViewportView(deskripsitxt);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(206, 306, 311, 96);

        jButton3.setText("CONTINUE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(280, 420, 110, 25);

        pembayaran.add(jPanel4);
        jPanel4.setBounds(160, 110, 570, 470);

        jPanel3.add(pembayaran, "card6");

        lunas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("TERIMAKASIH TELAH MELUNASI DAN MEMBAYAR SPP ANDA!!");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("PEMBAYARAN YANG ANDA LAKUKAN BERHASIL ");

        javax.swing.GroupLayout lunasLayout = new javax.swing.GroupLayout(lunas);
        lunas.setLayout(lunasLayout);
        lunasLayout.setHorizontalGroup(
            lunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lunasLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(lunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lunasLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lunasLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(92, 92, 92))))
        );
        lunasLayout.setVerticalGroup(
            lunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lunasLayout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(27, 27, 27)
                .addComponent(jLabel12)
                .addGap(271, 271, 271))
        );

        jPanel3.add(lunas, "card7");

        jPanel1.add(jPanel3);
        jPanel3.setBounds(180, 13, 870, 612);

        exitbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exitbtn.setText("X");
        exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbtnMouseClicked(evt);
            }
        });
        jPanel1.add(exitbtn);
        exitbtn.setBounds(1080, 0, 20, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 639);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        int logoutbtn = JOptionPane.YES_NO_OPTION;
        int logoutresult = JOptionPane.showConfirmDialog(this, "Are  You Sure Want To LogOut?!", "WARNING", logoutbtn);
        
        if (logoutresult == 0){
            LogIn menulogin = new LogIn();
            menulogin.setVisible(true);
            this.dispose();
            
        }else{
            
        }
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void aboutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutbtnActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        //add panel home
        jPanel3.add(aboutpanel);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_aboutbtnActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        //add panel home
        jPanel3.add(homepanel);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_homebtnActionPerformed

    private void exitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_exitbtnMouseClicked

    private void contactbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactbtnActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        //add panel home
        jPanel3.add(contactpanel);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_contactbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        //add panel home
        jPanel3.add(pembayaran);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String sql = "insert into tb_pembayaran values(?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(3, namafield.getText());
            stat.setString(2, kelasfield.getText());
            stat.setString(1, nisfield.getText());
            stat.setString(4, rekfield.getText());
            stat.setString(5, nominalfield.getText());
            stat.setString(6, deskripsitxt.getText());

            //if (isi_password.getText().equals(input_ulang_pass.getText())){
                if(namafield.getText().equals("") || namafield.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Tolong Masukan Data Anda");
                }else{
                    Connection konekDatabase = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/db_admsekolah", "root", "");

                    JOptionPane.showMessageDialog(this,"Pembayaran Berhasil","Notifikasi",JOptionPane.INFORMATION_MESSAGE);
                    stat.executeUpdate();
                    kosong();
                    

                    jPanel3.removeAll();
                    jPanel3.repaint();
                    jPanel3.revalidate();
        
                     //add panel home
                    jPanel3.add(lunas);
                    jPanel3.repaint();
                    jPanel3.revalidate();
                }
            //}else{
                //jLabel1.setText("Password yang anda masukkan salah !(red)" );
            //}

            namafield.requestFocus();

        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "PEMBAYARAN Anda Gagal" );
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutbtn;
    private javax.swing.JPanel aboutpanel;
    private javax.swing.JLabel aboutpng;
    private javax.swing.JPanel abstractpanel;
    private javax.swing.JButton contactbtn;
    private javax.swing.JPanel contactpanel;
    private javax.swing.JLabel contactpng;
    private javax.swing.JTextArea deskripsitxt;
    private javax.swing.JLabel exitbtn;
    private javax.swing.JButton homebtn;
    private javax.swing.JPanel homepanel;
    private javax.swing.JLabel homepng;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judulpng;
    private javax.swing.JTextField kelasfield;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JLabel logoutpng;
    private javax.swing.JPanel lunas;
    private javax.swing.JTextField namafield;
    private javax.swing.JTextField nisfield;
    private javax.swing.JTextField nominalfield;
    private javax.swing.JPanel pembayaran;
    private javax.swing.JTextField rekfield;
    // End of variables declaration//GEN-END:variables
}
