/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;
import com.mysql.jdbc.PreparedStatement;
import database.koneksi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.Timer;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import database.koneksi;
import java.sql.DriverManager;
import java.sql.ResultSet;

import user.LogIn;
import javax.swing.JOptionPane;

/**
 *
 * @author Yoga Asta
 */
public class dashboardframe1 extends javax.swing.JFrame {
    Connection conn = null;
    Statement pst = null;
    ResultSet rs = null;
    DefaultTableModel model = null;
   
    
    

    /**
     * Creates new form dashboardframe
     */
    public dashboardframe1() {
        initComponents();
        Tampil_Jam();
        Tampil_Tanggal();
    }
   

     public void Tampil_Jam(){
        ActionListener taskPerformer = new ActionListener() {
 
        @Override
            public void actionPerformed(ActionEvent evt) {
            String nol_jam = "", nol_menit = "",nol_detik = "";
 
            java.util.Date dateTime = new java.util.Date();
            int nilai_jam = dateTime.getHours();
            int nilai_menit = dateTime.getMinutes();
            int nilai_detik = dateTime.getSeconds();
 
            if(nilai_jam <= 9) nol_jam= "0";
            if(nilai_menit <= 9) nol_menit= "0";
            if(nilai_detik <= 9) nol_detik= "0";
 
            String jam = nol_jam + Integer.toString(nilai_jam);
            String menit = nol_menit + Integer.toString(nilai_menit);
            String detik = nol_detik + Integer.toString(nilai_detik);
 
            jLabel6.setText(jam+":"+menit+":"+detik+"");
            }
        };
    new Timer(1000, taskPerformer).start();
    }   
 
public void Tampil_Tanggal() {
    java.util.Date tglsekarang = new java.util.Date();
    SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
    String tanggal = smpdtfmt.format(tglsekarang);
    jLabel5.setText(tanggal);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        homepng = new javax.swing.JLabel();
        aboutpng = new javax.swing.JLabel();
        contactpng = new javax.swing.JLabel();
        logoutpng = new javax.swing.JLabel();
        homebtn = new javax.swing.JButton();
        aboutbtn = new javax.swing.JButton();
        contactbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        judulpng = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        abstractpanel = new javax.swing.JPanel();
        homepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        aboutpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        contactpanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelsiswa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbsiswa = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        panelpembayaran = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbpembayaran = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        exitbtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1102, 639));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1064, 639));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, new java.awt.Color(0, 0, 0), java.awt.Color.black, java.awt.Color.black));
        jPanel2.setLayout(null);

        homepng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/home.png"))); // NOI18N
        jPanel2.add(homepng);
        homepng.setBounds(10, 270, 50, 40);

        aboutpng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/information-button.png"))); // NOI18N
        jPanel2.add(aboutpng);
        aboutpng.setBounds(10, 350, 50, 40);

        contactpng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/call.png"))); // NOI18N
        jPanel2.add(contactpng);
        contactpng.setBounds(10, 430, 60, 40);

        logoutpng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/logout.png"))); // NOI18N
        jPanel2.add(logoutpng);
        logoutpng.setBounds(10, 530, 50, 30);

        homebtn.setBackground(new java.awt.Color(255, 255, 255));
        homebtn.setText("         HOME");
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        jPanel2.add(homebtn);
        homebtn.setBounds(10, 260, 133, 66);

        aboutbtn.setBackground(new java.awt.Color(255, 255, 255));
        aboutbtn.setText("         ABOUT");
        aboutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutbtnActionPerformed(evt);
            }
        });
        jPanel2.add(aboutbtn);
        aboutbtn.setBounds(14, 342, 133, 67);

        contactbtn.setBackground(new java.awt.Color(255, 255, 255));
        contactbtn.setText("           CONTACT");
        contactbtn.setIconTextGap(10);
        contactbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactbtnActionPerformed(evt);
            }
        });
        jPanel2.add(contactbtn);
        contactbtn.setBounds(14, 422, 133, 68);

        logoutbtn.setBackground(new java.awt.Color(255, 255, 255));
        logoutbtn.setText("       LOGOUT");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        jPanel2.add(logoutbtn);
        logoutbtn.setBounds(14, 508, 133, 66);

        judulpng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/mortarboard.png"))); // NOI18N
        jPanel2.add(judulpng);
        judulpng.setBounds(30, 30, 90, 90);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("E - ADMIN");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 110, 90, 40);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 160, 110, 16);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 200, 70, 17);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(12, 13, 160, 610);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jPanel3.setLayout(new java.awt.CardLayout());

        abstractpanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout abstractpanelLayout = new javax.swing.GroupLayout(abstractpanel);
        abstractpanel.setLayout(abstractpanelLayout);
        abstractpanelLayout.setHorizontalGroup(
            abstractpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
        );
        abstractpanelLayout.setVerticalGroup(
            abstractpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        jPanel3.add(abstractpanel, "card4");

        homepanel.setBackground(new java.awt.Color(255, 255, 255));
        homepanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("--HOME--");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/graduates (1).png"))); // NOI18N
        jButton1.setText("SISWA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/onboarding.png"))); // NOI18N
        jButton2.setText("PEGAWAI");

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/shopping-cart.png"))); // NOI18N
        jButton3.setText("PEMBAYARAN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/document.png"))); // NOI18N
        jButton4.setText("E-RAPOT");

        javax.swing.GroupLayout homepanelLayout = new javax.swing.GroupLayout(homepanel);
        homepanel.setLayout(homepanelLayout);
        homepanelLayout.setHorizontalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        homepanelLayout.setVerticalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        jPanel3.add(homepanel, "card2");

        aboutpanel.setBackground(new java.awt.Color(22, 160, 133));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("--ABOUT--");

        javax.swing.GroupLayout aboutpanelLayout = new javax.swing.GroupLayout(aboutpanel);
        aboutpanel.setLayout(aboutpanelLayout);
        aboutpanelLayout.setHorizontalGroup(
            aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutpanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addContainerGap(746, Short.MAX_VALUE))
        );
        aboutpanelLayout.setVerticalGroup(
            aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutpanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addContainerGap(550, Short.MAX_VALUE))
        );

        jPanel3.add(aboutpanel, "card3");

        contactpanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("--CONTACT-- ");

        javax.swing.GroupLayout contactpanelLayout = new javax.swing.GroupLayout(contactpanel);
        contactpanel.setLayout(contactpanelLayout);
        contactpanelLayout.setHorizontalGroup(
            contactpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactpanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(727, Short.MAX_VALUE))
        );
        contactpanelLayout.setVerticalGroup(
            contactpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactpanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(561, Short.MAX_VALUE))
        );

        jPanel3.add(contactpanel, "card5");

        panelsiswa.setBackground(new java.awt.Color(255, 255, 255));
        panelsiswa.setLayout(null);

        tbsiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbsiswa);

        panelsiswa.add(jScrollPane1);
        jScrollPane1.setBounds(0, 130, 866, 480);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("DATA AKUN SISWA");
        panelsiswa.add(jLabel7);
        jLabel7.setBounds(330, 70, 230, 40);

        jPanel3.add(panelsiswa, "card6");

        panelpembayaran.setBackground(new java.awt.Color(255, 255, 255));

        tbpembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbpembayaran);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("DATA PEMBAYARAN SISWA");

        javax.swing.GroupLayout panelpembayaranLayout = new javax.swing.GroupLayout(panelpembayaran);
        panelpembayaran.setLayout(panelpembayaranLayout);
        panelpembayaranLayout.setHorizontalGroup(
            panelpembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(panelpembayaranLayout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel9)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        panelpembayaranLayout.setVerticalGroup(
            panelpembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpembayaranLayout.createSequentialGroup()
                .addGap(0, 125, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(panelpembayaran, "card7");

        jPanel1.add(jPanel3);
        jPanel3.setBounds(180, 13, 870, 612);

        exitbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exitbtn.setText("X");
        exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbtnMouseClicked(evt);
            }
        });
        jPanel1.add(exitbtn);
        exitbtn.setBounds(1080, 0, 20, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 639);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        int logoutbtn = JOptionPane.YES_NO_OPTION;
        int logoutresult = JOptionPane.showConfirmDialog(this, "Are  You Sure Want To LogOut?!", "WARNING", logoutbtn);
        
        if (logoutresult == 0){
            loginadmin menulogin = new loginadmin();
            menulogin.setVisible(true);
            this.dispose();
            
        }else{
            
        }
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void aboutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutbtnActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        //add panel home
        jPanel3.add(aboutpanel);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_aboutbtnActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        //add panel home
        jPanel3.add(homepanel);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_homebtnActionPerformed

    private void exitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_exitbtnMouseClicked

    private void contactbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactbtnActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        //add panel home
        jPanel3.add(contactpanel);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_contactbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        //add panel home
        jPanel3.add(panelsiswa);
        jPanel3.repaint();
        jPanel3.revalidate();
        
       String[] header = {"nama","alamat","email","pass"};
       model = new DefaultTableModel(header,0);
       tbsiswa.setModel(model);
       
       koneksi classkoneksi = new koneksi(); 
        try{
           conn = classkoneksi.getkoneksi();
            pst = conn.createStatement();
            rs = pst.executeQuery("SELECT * FROM tb_user");
            
            //String sql= "SELECT * FROM tb_user";
            while(rs.next()){
            String[] row = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
            model.addRow(row); 
            }
            tbsiswa.setModel(model);
            }catch(SQLException e){
                System.out.print(e.getMessage());
}
       
        
        
    
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        //add panel home
        jPanel3.add(panelpembayaran);
        jPanel3.repaint();
        jPanel3.revalidate();
        
       String[] header = {"nis","kelas","nama","norek","nominal","deskripsi"};
       model = new DefaultTableModel(header,0);
       tbpembayaran.setModel(model);
       
       koneksi classkoneksi = new koneksi(); 
        try{
           conn = classkoneksi.getkoneksi();
            pst = conn.createStatement();
            rs = pst.executeQuery("SELECT * FROM tb_pembayaran");
            
            //String sql= "SELECT * FROM tb_user";
            while(rs.next()){
            String[] row = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)};
            model.addRow(row); 
            }
            tbsiswa.setModel(model);
            }catch(SQLException e){
                System.out.print(e.getMessage());
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardframe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardframe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardframe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardframe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardframe1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutbtn;
    private javax.swing.JPanel aboutpanel;
    private javax.swing.JLabel aboutpng;
    private javax.swing.JPanel abstractpanel;
    private javax.swing.JButton contactbtn;
    private javax.swing.JPanel contactpanel;
    private javax.swing.JLabel contactpng;
    private javax.swing.JLabel exitbtn;
    private javax.swing.JButton homebtn;
    private javax.swing.JPanel homepanel;
    private javax.swing.JLabel homepng;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel judulpng;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JLabel logoutpng;
    private javax.swing.JPanel panelpembayaran;
    private javax.swing.JPanel panelsiswa;
    private javax.swing.JTable tbpembayaran;
    private javax.swing.JTable tbsiswa;
    // End of variables declaration//GEN-END:variables
}
