/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;
import header.Headerframe;
/**
 *
 * @author Yoga Asta
 */

import database.koneksi;
import user.forgot_pass;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class loginadmin extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Object set;
    
    public loginadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        tbl_mimizenexit = new javax.swing.JLabel();
        judul_menu_login = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        lupa_pass = new javax.swing.JLabel();
        isi_username = new javax.swing.JTextField();
        isi_pass = new javax.swing.JPasswordField();
        tbl_reg = new javax.swing.JButton();
        tbl_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1179, 663));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1179, 663));
        getContentPane().setLayout(null);

        jPanel3.setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 0));
        kGradientPanel1.setLayout(null);

        tbl_mimizenexit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbl_mimizenexit.setText("   X");
        tbl_mimizenexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mimizenexitMouseClicked(evt);
            }
        });
        kGradientPanel1.add(tbl_mimizenexit);
        tbl_mimizenexit.setBounds(1140, 0, 40, 40);

        judul_menu_login.setFont(new java.awt.Font("News701 BT", 1, 24)); // NOI18N
        judul_menu_login.setText("=LOGIN=");
        kGradientPanel1.add(judul_menu_login);
        judul_menu_login.setBounds(550, 120, 140, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jPanel2.setLayout(null);

        username.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        username.setText("USERNAME");
        jPanel2.add(username);
        username.setBounds(80, 160, 76, 19);

        pass.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        pass.setText("PASSWORD");
        jPanel2.add(pass);
        pass.setBounds(80, 250, 76, 19);

        lupa_pass.setForeground(new java.awt.Color(255, 51, 51));
        lupa_pass.setText("FORGOT PASSWORD?");
        lupa_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupa_passMouseClicked(evt);
            }
        });
        jPanel2.add(lupa_pass);
        lupa_pass.setBounds(280, 390, 140, 16);

        isi_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        isi_username.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        isi_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isi_usernameActionPerformed(evt);
            }
        });
        jPanel2.add(isi_username);
        isi_username.setBounds(220, 160, 300, 30);

        isi_pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        isi_pass.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(isi_pass);
        isi_pass.setBounds(220, 240, 300, 30);

        tbl_reg.setBackground(new java.awt.Color(255, 255, 255));
        tbl_reg.setText("SIGN UP");
        tbl_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl_regActionPerformed(evt);
            }
        });
        jPanel2.add(tbl_reg);
        tbl_reg.setBounds(300, 350, 90, 25);

        tbl_login.setBackground(new java.awt.Color(255, 255, 255));
        tbl_login.setText("SIGN IN");
        tbl_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl_loginActionPerformed(evt);
            }
        });
        jPanel2.add(tbl_login);
        tbl_login.setBounds(300, 305, 90, 30);

        kGradientPanel1.add(jPanel2);
        jPanel2.setBounds(280, 170, 650, 460);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/login.png"))); // NOI18N
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(550, 30, 120, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/previous (1).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(20, 10, 40, 40);

        jPanel3.add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 1180, 660);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1180, 660);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl_loginActionPerformed
        // TODO add your handling code here:
        conn = koneksi.getkoneksi();
        String sql = "SELECT * FROM tb_admin WHERE nama=? and password=?";
        try{
            pst = (PreparedStatement)conn.prepareStatement(sql);
            pst.setString(1, isi_username.getText());
            pst.setString(2, isi_pass.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Aktivitas Login Anda Sukses!!");
                dashboardframe1 framedashboard = new dashboardframe1();
                framedashboard.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Data Yang Anda Masukan Salah!!!", "Pesan", JOptionPane.ERROR_MESSAGE);
               
                isi_username.setText("");
                isi_pass.setText("");
            }
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
     
    }//GEN-LAST:event_tbl_loginActionPerformed

    private void isi_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isi_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isi_usernameActionPerformed

    private void tbl_mimizenexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mimizenexitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tbl_mimizenexitMouseClicked

    private void tbl_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl_regActionPerformed
        // TODO add your handling code here:
        regisadmin frameregis = new regisadmin();
        frameregis.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_tbl_regActionPerformed

    private void lupa_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupa_passMouseClicked
        // TODO add your handling code here:
        forgot_pass lupa_pass = new forgot_pass();
        lupa_pass.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lupa_passMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Headerframe header = new Headerframe();
        header.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField isi_pass;
    private javax.swing.JTextField isi_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel judul_menu_login;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lupa_pass;
    private javax.swing.JLabel pass;
    private javax.swing.JButton tbl_login;
    private javax.swing.JLabel tbl_mimizenexit;
    private javax.swing.JButton tbl_reg;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
